"""Validation and deterministic normalization for generated images."""

from __future__ import annotations

from io import BytesIO

from PIL import Image, ImageOps, UnidentifiedImageError


class ImageProcessingError(ValueError):
    """Raised when model output cannot safely be used as an invitation image."""


class ImageProcessor:
    """Turn model output into a metadata-free RGB PNG of a fixed size."""

    def __init__(
        self,
        width: int = 705,
        height: int = 1280,
        *,
        max_input_bytes: int = 20 * 1024 * 1024,
    ) -> None:
        if width < 1 or height < 1:
            raise ValueError("Output dimensions must be positive")
        self.width = width
        self.height = height
        self.max_input_bytes = max_input_bytes

    def normalize_png(self, data: bytes) -> bytes:
        """Decode, center-crop, resize and encode image bytes as PNG."""

        if not data:
            raise ImageProcessingError("Generated image is empty")
        if len(data) > self.max_input_bytes:
            raise ImageProcessingError("Generated image exceeds the configured size limit")

        try:
            with Image.open(BytesIO(data)) as source:
                source.load()
                image = ImageOps.exif_transpose(source)
                if image.width < 128 or image.height < 128:
                    raise ImageProcessingError("Generated image dimensions are too small")
                if image.mode in {"RGBA", "LA"} or "transparency" in image.info:
                    rgba = image.convert("RGBA")
                    white = Image.new("RGBA", rgba.size, "white")
                    white.alpha_composite(rgba)
                    image = white.convert("RGB")
                else:
                    image = image.convert("RGB")
                normalized = ImageOps.fit(
                    image,
                    (self.width, self.height),
                    method=Image.Resampling.LANCZOS,
                    centering=(0.5, 0.5),
                )
        except ImageProcessingError:
            raise
        except (UnidentifiedImageError, OSError, ValueError) as exc:
            raise ImageProcessingError("Generated bytes are not a valid image") from exc

        output = BytesIO()
        normalized.save(output, format="PNG", optimize=True)
        result = output.getvalue()
        if not result.startswith(b"\x89PNG\r\n\x1a\n"):
            raise ImageProcessingError("PNG encoding failed")
        return result

